Fix updating of version in new SPEC file
Fixing:
$ python ~/devel/projects/rebase-helper/rebase-helper.py
--buildtool=rpmbuild wget-1.15.tar.xz
Results directory 'rebase-helper-results' exists, removing it
Results directory 'rebase-helper-results' exists, removing it
error: line 3: Illegal char '-' in: Version: wget-1.15.tar.xz
Traceback (most recent call last):
    File "/home/thozza/devel/projects/rebase-helper/rebase-helper.py",
    line 43, in <module>
    sys.exit(main(sys.argv[1:]))
    File
    "/home/thozza/devel/projects/rebase-helper/rebase-helper.py",
    line 31, in main
    app = Application(cli)
    File
    "/home/thozza/devel/projects/rebase-helper/rebasehelper/application.py",
    line 70, in __init__
    self._prepare_spec_objects()
    File
    "/home/thozza/devel/projects/rebase-helper/rebasehelper/application.py",
    line 112, in _prepare_spec_objects
    download=not self.conf.not_download_sources)
    File
    "/home/thozza/devel/projects/rebase-helper/rebasehelper/specfile.py",
    line 81, in __init__
    self.set_spec_version()
    File
    "/home/thozza/devel/projects/rebase-helper/rebasehelper/specfile.py",
    line 310, in set_spec_version
    self._update_spec_version(self.spec_content)
    File
    "/home/thozza/devel/projects/rebase-helper/rebasehelper/specfile.py",
    line 286, in _update_spec_version
    self._update_data()
    File
    "/home/thozza/devel/projects/rebase-helper/rebasehelper/specfile.py",
    line 89, in _update_data
    self.spc =
    rpm.spec(self.spec_file)
    ValueError: can't parse
                specfile

Signed-off-by: Tomas Hozza <thozza@redhat.com>